// 全画面共通のレイアウト
import Link from "next/link"
import { Suspense } from "react"
import '../styles/global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <body>
        <Suspense>
        {/* <div className="header">
          <Link href={"/"}>/Home</Link>
          <Link href={"/Start"}>/Start</Link>
          <Link href={"/Develop"}>/Develop</Link>
          <Link href={"/Story"}>/Story</Link>
          <Link href={"/Ending"}>/Ending</Link>
        </div> */}

        <div>{children}</div>
        </Suspense>
      </body>
    </html>
  )
}
